In [ ]:
# Initialize Otter
import otter
grader = otter.Notebook("check_matrices.ipynb")

# Instructions

Overview slides are here https://docs.google.com/presentation/d/1nTexr-lPdkq3HW4ouzYTa9iEiO-6K7j5ihHvZqixIsM/edit?usp=sharing

Slides specific to this assignment are here: https://docs.google.com/presentation/d/1iTi45y5AghMZRgStPX4mPdR7uYFQdRBjaekOW7ESTxM/edit?usp=sharing
You will be editing matrix_transforms.py for this assignment

This is just setting up (and analyzing) 2 dimensional matrices (rotation, translation, scaling).

In [1]:
# Doing the imports for you
import numpy as np
import matplotlib.pyplot as plt

# Since we need so many of the functions in matrix_transforms, I'm using this style of import. Anything with
# an mt. in front of it comes from matrix_transforms.py
import matrix_transforms as mt

# These commands will force JN to actually re-load the external file when you re-execute this import command
%load_ext autoreload
%autoreload 2

# Get rid of annoying exponentials
np.set_printoptions(precision=2, suppress='True')

# Making matrices 
This bit of code checks that the make_x_matrix routines (and their corresponding get_x_ routines) are working.

You shouldn't have to edit any of this code; just the functions in matrix_transforms.py.

_Type your answer here, replacing this text._

In [2]:
# Should have 0.1 in the upper right corner, with 0.2 in the next row down
mat_trans = mt.make_translation_matrix(0.1, 0.2)
print(f"Matrix:\n{mat_trans}\nMatrix shape:{mat_trans.shape}")
assert(mat_trans.shape == (3, 3))

Matrix:
[[1.  0.  0.1]
 [0.  1.  0.2]
 [0.  0.  1. ]]
Matrix shape:(3, 3)


In [3]:
# Should have 0.1 then 0.2 on the diagonal
mat_scale = mt.make_scale_matrix(0.1, 0.2)
print(f"Matrix:\n{mat_scale}\nMatrix shape:{mat_scale.shape}")
assert(mat_scale.shape == (3, 3))

Matrix:
[[0.1 0.  0. ]
 [0.  0.2 0. ]
 [0.  0.  1. ]]
Matrix shape:(3, 3)


In [4]:
# Should have 0.866 on the diagonal, -0.5 and 0.5 on the off-axis
mat_rot = mt.make_rotation_matrix(np.pi / 6.0)
print(f"Matrix:\n{mat_rot}\nMatrix shape:{mat_rot.shape}")
assert(mat_rot.shape == (3, 3))

Matrix:
[[ 0.87 -0.5   0.  ]
 [ 0.5   0.87  0.  ]
 [ 0.    0.    1.  ]]
Matrix shape:(3, 3)


In [5]:
# Get back out what you put in
dx = 0.1
dy = 0.2
mat_trans = mt.make_translation_matrix(dx, dy)
dx_back, dy_back = mt.get_dx_dy_from_matrix(mat_trans)
print(f"Got back {dx_back}, {dy_back}")
assert(np.isclose(dx, dx_back))
assert(np.isclose(dy, dy_back))

Got back 0.1, 0.2


In [6]:
# Get back out what you put in
sx = 0.1
sy = 0.2
mat_scale = mt.make_scale_matrix(sx, sy)
sx_back, sy_back = mt.get_sx_sy_from_matrix(mat_scale)
print(f"Got back {sx_back}, {sy_back}")
assert(np.isclose(sx, sx_back))
assert(np.isclose(sy, sy_back))

Got back 0.1, 0.2


In [19]:
# Get back out what you put in
theta = np.pi / 2.0
mat_rot = mt.make_rotation_matrix(theta)

v_new_x, v_new_y = mt.get_axes_from_matrix(mat_rot)
print(f"Got back vec {v_new_x} and {v_new_y}")

vec_expected_x = np.array([0.0, 1.0])
vec_expected_y = np.array([-1.0, 0.0])
assert(np.all(np.isclose(v_new_x, vec_expected_x)))
assert(np.all(np.isclose(v_new_y, vec_expected_y)))

theta_back = mt.get_theta_from_matrix(mat_rot)
print(f"Sent {theta} got back {theta_back}")
assert(np.isclose(theta, theta_back))

Got back vec [[0.]
 [1.]
 [0.]] and [[-1.]
 [ 0.]
 [ 0.]]


AssertionError: 

In [9]:
# Call each of the test routines in turn
mt.test_matrices()

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 1. -0.  0.]
 [-0.  1.  0.]
 [ 0.  0.  1.]]


True

In [ ]:
grader.check("making_matrices")

# Check matrices
These are the checks you need to make sure your matrices are what you expect they are (angle-preserving, no mirroring). 

These are the check_x routines in matrix_transforms.py. Note that this is just test_checks pulled apart into each check call. You don't have to change any of this code; see the slides for what this should output

In [10]:
mat_not_orthonormal = np.identity(3)
mat_not_orthonormal[0, 0] = 2.0
if mt.check_is_rotation(mat_not_orthonormal, b_print=True):
    raise ValueError(f"Matrix {mat_not_orthonormal} is not orthonormal, should fail length check")

[[4. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
True


In [11]:
mat_not_orthonormal = np.identity(3)

mat_not_orthonormal[1, 1] = np.sqrt(1.0 - 0.1 * 0.1)
mat_not_orthonormal[1, 0] = 0.1

if mt.check_is_rotation(mat_not_orthonormal, True):
    raise ValueError(f"Matrix {mat} is not orthonormal, should fail orthogonal check")

[[1.  0.1 0. ]
 [0.1 1.  0. ]
 [0.  0.  1. ]]
True


In [12]:
mat_mirrored = mt.make_scale_matrix(2.0, -1.2)
if not mt.check_is_mirrored(mat_mirrored):
    raise ValueError(f"Matrix {mat_mirrored} is mirrored, should return True")

In [13]:
mat_skewed = mt.make_scale_matrix(2.0, 1.2) @ mt.make_rotation_matrix(0.25)
if mt.check_preserves_angles(mat_skewed):
    raise ValueError(f"Matrix {mat_skewed} does NOT preserve angles, should return False")

[[1.94 0.3  0.  ]] [[-0.49]
 [ 1.16]
 [ 0.  ]]
Dot Product
[[-0.61]]
[[False]]


In [14]:
mat_is_ok = mt.make_rotation_matrix(np.pi/3.0) @ mt.make_translation_matrix(0.2, -0.3) @ mt.make_rotation_matrix(-np.pi/2.0) @ mt.make_scale_matrix(0.2, 2.0)
if mt.check_is_mirrored(mat_is_ok):
    raise ValueError(f"Matrix {mat_is_ok} is NOT mirrored, should return False")
if not mt.check_preserves_angles(mat_is_ok):
    raise ValueError(f"Matrix {mat_is_ok} is angle-preserving, should return True")
if mt.check_is_rotation(mat_is_ok):
    raise ValueError(f"Matrix {mat_is_ok} is NOT orthonormal, should return False")


[[ 0.17 -0.1   0.  ]] [[1.  ]
 [1.73]
 [0.  ]]
Dot Product
[[-0.]]
[[ True]]
[[1.16 1.72 0.36]
 [1.72 3.01 0.02]
 [0.36 0.02 1.  ]]
False


In [15]:
mat_is_ortho = mt.make_rotation_matrix(np.pi/3.0) @ mt.make_rotation_matrix(-np.pi/2.0)
mat_is_not_ortho = mt.make_rotation_matrix(np.pi/3.0) @ mt.make_translation_matrix(0.2, -0.3) @ mt.make_rotation_matrix(-np.pi/2.0)
if not mt.check_is_rotation(mat_is_ortho):
    raise ValueError(f"Matrix {mat_is_ortho} is orthonormal, should return True")
if mt.check_is_rotation(mat_is_not_ortho):
    raise ValueError(f"Matrix {mat_is_not_ortho} is NOT orthonormal, should return False")

[[ 1. -0.  0.]
 [-0.  1.  0.]
 [ 0.  0.  1.]]
[[1.13 0.01 0.36]
 [0.01 1.   0.02]
 [0.36 0.02 1.  ]]
False


In [ ]:
grader.check("check_matrices")

<!-- BEGIN QUESTION -->

# Set up the XY matrix for drawing

Edit make_matrix_from_sequence to actually build a matrix sequence.
Edit make_pts_representing_circle to make a matrix representing the points on the circle,
Edit plot_axes_and_circle to create the XY vertices/geometry for drawing a circle.
Note that I'm using make_matrix_from_sequence for these examples; it will call the mak

In [16]:
# Check syntax of call
seq_rot_trans = [{"type":"rotate", "theta": np.pi/4.0},
                 {"type":"translate", "dx": 1, "dy": 2}]

mat = mt.make_matrix_from_sequence(seq_rot_trans)
print(f"Matrix:\n{mat}")

Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
# Check syntax of call
pts = mt.make_pts_representing_circle(25)
print(pts)
assert(pts.shape == (3, 25))

NameError: name 'pts' is not defined

In [ ]:
# Syntax/draws correctly check (just one plot)
fig, axs = plt.subplots(2, 2)


axs[0, 0].set_title("Rot trans")
mt.plot_axes_and_circle(axs[0, 0], mat)

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

# Order matters
Edit example_order_matters() to create the plot shown in the slides.

Which one of these four transformations is NOT angle-preserving? Why?

In [ ]:
mt.example_order_matters()

In [ ]:
# Edit this line of code
print("?? is NOT angle preserving, because...")

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

# Mirroring and skewing
In this problem, edit example_weird_geometry to create a mirror and a non-angle preserving matrix. The slides show the ones I made; there are an infinite number of choices. 

In [ ]:
mt.example_weird_geometry()

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

# Geometry is NOT centered around the origin
Edit example_uncentered_geometry to create versions of the circle and the zigzag that are in other configurations.
- Put the orgin in the lower left (-1, -1), rather than the center. This is a pretty common placement.
- Orient so that the "up" direction is no longer the y-axis, but is the x-axis. 
- Do both

The matrix transformation applied to the geometry is the SAME for all of these plots - it's represented by the red,blue lines. It's just the geometry that has moved.

In [ ]:
mt.example_uncentered_geometry()

<!-- END QUESTION -->

## Hours and collaborators
Required for every assignment - fill out before you hand-in.

Listing names and websites helps you to document who you worked with and what internet help you received in the case of any plagiarism issues. You should list names of anyone (in class or not) who has substantially helped you with an assignment - or anyone you have *helped*. You do not need to list TAs.

Listing hours helps us track if the assignments are too long.

In [ ]:

# List of names (creates a set)
worked_with_names = {"N/A"}
# List of URLS (creates a set)
websites = {"numpy.com"}
# Approximate number of hours, including lab/in-class time
hours = 4

# for all row, column in all_indices_from_where
#.   if this is the column for wrist torque 
#.      print(f"Row: {r}, Time step: {c // n_time_steps} Successful y/n: {pick_data[r, -1] == 1}, value: {pick_data[r, c]}")

In [ ]:
grader.check("hours_collaborators")

---

To double-check your work, the cell below will rerun all of the autograder tests.

In [ ]:
grader.check_all()

## Submission

Make sure you have run all cells in your notebook in order before running the cell below, so that all images/graphs appear in the output. The cell below will generate a zip file for you to submit. **Please save before exporting!**

Submit through gradescope, matrix transforms

In [ ]:
# Save your notebook first, then run this cell to export your submission.
grader.export()